#!/usr/bin/env bash

count=$3
file=$2
block=$1
awk "BEGIN { RS=\"}%\"; FS=\"%{\" } { if (NR<=$count) {printf \"%s}%\",\$0}}" $file | rev | tac | \
    awk "BEGIN { RS=\"%}\"; FS=\"{%\"; c=0; v=0 } { 
	    for (i=1;i<=NF;i++) {
		    if (i>1) c--;
		    if (c==0 && !(i==1 && NR==1) ) v=1;
		    if (v==1) { 
			    if (i==1) printf \"%}\";
			    if (i>1) printf \"{%\";
			    printf \"%s\",\$i 
		    }
	    };
	    if (NF==0 && NR>2) printf \"%}\";
	    c++; 
    } " | rev | tac | perl -pe 'chomp if eof' | sed '$s/%{$//'
perl -pe 'chomp if eof' $block
awk "BEGIN { RS=\"}%\"; FS=\"%{\" } { if (NR>$count) {printf \"%s}%\",\$0}}" $file | sed '$d'
