#!/usr/bin/env bash

count=$2
file=$1
awk "BEGIN { RS=\"}%\"; FS=\"%{\" } { if (NR<=$count) {printf \"%s}%\",\$0}}" $file | rev | tac | \
    awk "BEGIN { RS=\"%}\"; FS=\"{%\"; c=0 } { 
	    for (i=1;i<=NF;i++) {
		    if (i>1) c--;
		    if (c>0) { 
			    if (i==1 && NR>2) printf \"%}\";
			    if (i>1) printf \"{%\";
			    printf \"%s\",\$i 
		    }
		    if (c==0 && !(i==1 && NR==1) ) exit;
	    };
	    c++; 
    } " | rev | tac
