#!/usr/bin/env bash

key=$1
file_keys=$2
rt=0

[[ -z "$key" ]] || [[ -z "$file_keys" ]] && echo "Usage: get-key <key> <file>" && exit 2
[[ ! -e "$file_keys" ]] && echo "file '$file_keys' not found" && exit 3

if [ $(grep -c "^- $key:$" $file_keys) -gt 0 ]; then
	sed -n "/^- $key:$/,/^- .*:$/p" $file_keys | sed '/^- .*:$/d' 
else
	rc=1
fi

exit $rc
