#!/usr/bin/env bash

info=$1
file=$2

# info is one of:
# name title path depends fullpathname

[[ -z "$info" ]] || [[ -z "$file" ]] && echo "Usage: info <info> <file>" && exit 2
[[ ! -e "$file" ]] && echo "file '$file' not found" && exit 3

case $info in
	"name") 
		name=$($SHS2_PATH/shsite2-get-key $file name | $SHS2_PATH/shsite2-parse $file)
		[[ -z "$name" ]] && name=$($SHS2_PATH/shsite2-get-key $file filename | $SHS2_PATH/shsite2-parse $file)
		[[ -z "$name" ]] && { 
			name=${file##*/}
			name=${name/.sl/.html}
		}
		echo "$name"
		;;
	"title") 
		title=$($SHS2_PATH/shsite2-get-key $file title | $SHS2_PATH/shsite2-parse $file)
		[[ -z "$title" ]] && { title=${file##*/}; title=${title%.*}; }
		echo "$title"
		;;
	"path") 
		path=$($SHS2_PATH/shsite2-get-key $file path | $SHS2_PATH/shsite2-parse $file)
		[[ -z "$path" ]] && path=$(dirname $file)
		[[ "$path" = "." ]] && path=""
		echo "$path"
		;;
	"fullpathname")
		path=$($SHS2_PATH/shsite2-info path $file)
		name=$($SHS2_PATH/shsite2-info name $file)
		if [[ -z "$path" ]]; then echo "$name"; else echo "$path/$name"; fi
		;;
	"depends") 
		depends=($($SHS2_PATH/shsite2-get-key $file depends | $SHS2_PATH/shsite2-parse $file))
		depends+=($(grep -o "%{@[^}]*}%" $file | sed 's/^%{@//;s/}%$//'))
		echo $(for i in "${depends[@]}"; do
			([[ -e $i ]] && echo "$i") || \
				([[ -e $SHS2_LIB_PATH/$i ]] && echo "$SHS2_LIB_PATH/$i" ) || \
				([[ -e $USER_INC_PATH/$i ]] && echo "$USER_INC_PATH/$i")
		done | sort | uniq | xargs)
		;;
	*)
		echo "<info> should be one of: path, name, fullpathname, title, depends."
		exit 2
		;;
esac
