#!/usr/bin/env bash

eval "set $1"

[[ -e "$1.db" ]] && db=$1.db
[[ -z "$db" ]] && db=$1
selector=$2
[[ -z "$selector" ]] && selector='*'
[[ ! -z "$3" ]] && where=" WHERE $3 "
sqlite3 $db "SELECT $selector FROM posts $where" | sed "s/|/' '/g;s/^/\"'/;s/$/'\"/"
