#!/usr/bin/env bash

eval "set $1"

[[ -e "$1.db" ]] && db=$1.db
[[ -z "$db" ]] && db=$1
selector=$2
[[ -z "$selector" ]] && selector='*'
sqlite3 $db "SELECT $selector FROM posts GROUP BY created_timestamp" | sed "s/|/' '/g;s/^/\"'/;s/$/'\"/"
